%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-cob-driver
Version:        0.7.5
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS cob_driver package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_driver
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-noetic-cob-base-drive-chain
Requires:       ros-noetic-cob-bms-driver
Requires:       ros-noetic-cob-canopen-motor
Requires:       ros-noetic-cob-elmo-homing
Requires:       ros-noetic-cob-generic-can
Requires:       ros-noetic-cob-light
Requires:       ros-noetic-cob-mimic
Requires:       ros-noetic-cob-phidgets
Requires:       ros-noetic-cob-relayboard
Requires:       ros-noetic-cob-scan-unifier
Requires:       ros-noetic-cob-sick-lms1xx
Requires:       ros-noetic-cob-sick-s300
Requires:       ros-noetic-cob-sound
Requires:       ros-noetic-cob-undercarriage-ctrl
Requires:       ros-noetic-cob-utilities
Requires:       ros-noetic-cob-voltage-control
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The cob_driver stack includes packages that provide access to the Care-O-bot
hardware through ROS messages, services and actions. E.g. for mobile base, arm,
camera sensors, laser scanners, etc...

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Apr 06 2021 Felix Messmer <felixmessmer@gmail.com> - 0.7.5-1
- Autogenerated by Bloom

* Wed Oct 14 2020 Felix Messmer <felixmessmer@gmail.com> - 0.7.4-1
- Autogenerated by Bloom

