%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-cob-driver
Version:        0.7.1
Release:        1%{?dist}
Summary:        ROS cob_driver package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_driver
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-cob-base-drive-chain
Requires:       ros-melodic-cob-bms-driver
Requires:       ros-melodic-cob-camera-sensors
Requires:       ros-melodic-cob-canopen-motor
Requires:       ros-melodic-cob-elmo-homing
Requires:       ros-melodic-cob-generic-can
Requires:       ros-melodic-cob-light
Requires:       ros-melodic-cob-mimic
Requires:       ros-melodic-cob-phidgets
Requires:       ros-melodic-cob-relayboard
Requires:       ros-melodic-cob-scan-unifier
Requires:       ros-melodic-cob-sick-lms1xx
Requires:       ros-melodic-cob-sick-s300
Requires:       ros-melodic-cob-sound
Requires:       ros-melodic-cob-undercarriage-ctrl
Requires:       ros-melodic-cob-utilities
Requires:       ros-melodic-cob-voltage-control
BuildRequires:  ros-melodic-catkin

%description
The cob_driver stack includes packages that provide access to the Care-O-bot
hardware through ROS messages, services and actions. E.g. for mobile base, arm,
camera sensors, laser scanners, etc...

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Thu Nov 07 2019 Felix Messmer <felixmessmer@gmail.com> - 0.7.1-1
- Autogenerated by Bloom

* Tue Aug 06 2019 Felix Messmer <felixmessmer@gmail.com> - 0.7.0-1
- Autogenerated by Bloom

