%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-cob-undercarriage-ctrl
Version:        0.7.1
Release:        1%{?dist}
Summary:        ROS cob_undercarriage_ctrl package

License:        Apache 2.0
URL:            http://ros.org/wiki/cob_undercarriage_ctrl
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-cob-msgs
Requires:       ros-melodic-cob-utilities
Requires:       ros-melodic-control-msgs
Requires:       ros-melodic-diagnostic-msgs
Requires:       ros-melodic-diagnostic-updater
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-tf
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cob-msgs
BuildRequires:  ros-melodic-cob-utilities
BuildRequires:  ros-melodic-control-msgs
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-diagnostic-updater
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-tf

%description
cob_undercarriage_ctrl implements a controller for the omnidirectional base of
Care-O-bot 3 on joint level. For a given Pltf-Twist the according wheel steering
angles and linear wheel velocities are calculated based on the principle of
rigid body motion. Each joint is than controlled individually to achieve the
computed position and velocity

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Thu Nov 07 2019 Matthias Gruhler <mig@ipa.fhg.de> - 0.7.1-1
- Autogenerated by Bloom

* Tue Aug 06 2019 Matthias Gruhler <mig@ipa.fhg.de> - 0.7.0-1
- Autogenerated by Bloom

